### ISSUE TITLE
関連情報のレイアウトについて

### ISSUE THREAD

**Issue by kazutan** [kazutan/DBDA2E-ja#11]
関連情報のページについてですが，タブ構成にしようと思います。

- イベント
  - セミナーや読書会など
- ブログ紹介
  - 紹介してもらった記事をリストアップ
- その他
  - 関連書籍とかリンクとか?

こういうのをイメージしてます。いかがでしょうか? @kosugitti

**Comment by kosugitti** [comment]
LGTM！

**Comment by kazutan** [comment]
了解です! それではその方向で進めます!

**Comment by kazutan** [comment]
変更してmergeしたので，このissueを閉じます。
