### ISSUE TITLE
エクササイズ6.4. のヒント「一番下段の左」は上段の左？

### ISSUE THREAD

**Issue by 3100** [kazutan/DBDA2E-ja#4]
素晴らしい本が翻訳で読め、またそのサポートサイトがgithubで開設されたことに、大変感謝しております。

さて、表題に関してですが、原著ではupper-left panelとあるようです。
エクササイズの趣旨的にも、「一番上段の左」を指すのではないかと思いましたがいかがでしょうか。

**Comment by kazutan** [comment]
@3100 この度は本書をお手にとっていただき、ありがとうございます。

原著を確認したところ、おっしゃるとおりでした。ご指摘ありがとうございます。速やかに正誤表に記載したいと思います。今後共どうぞ何卒よろしくお願いいたします。

**Comment by kazutan** [comment]
正誤表に反映いたしました。また何かお気づきの点がございましたら、ご連絡いただけると助かります。ありがとうございました。
